GET http://localhost:5000/todos

###
GET http://localhost:5000/todos/1

###
POST http://localhost:5000/todos
Content-Type: application/json

{
    "title" : "Belajar Frontend",
    "deadline": "2025-01-10",
    "completed": true
}

###
PATCH http://localhost:5000/todos/4
Content-Type: application/json

{
    "title" : "Belajar Backend",
    "deadline": "2025-01-10",
    "completed": true
}

###
DELETE  http://localhost:5000/todos/6